[project]
name = "Livt.Collections"
version = "1.1.0-dev"
path = "src"
outdir = "out"

[tests]
path = "tests"
components = [
    "GenericCollectionsTest",
    "QueueInterfaceTest",
    "GenericQueueTest",
    "ConcurrentQueueTest",
    "QueueCapacityTest",
    "QueueClearConcurrencyTest",
    "ListIteratorTest",
    "Queue8Test",
    "Queue16Test",
    "Queue32Test",
    "Queue64Test",
    "Stack8Test",
    "Stack16Test",
    "Stack32Test",
    "Stack64Test",
    "CircularBufferTest",
    "ListTest",
    "BitSet8Test"
]

[build.debug]
warnings = ["all"]

[build.release]
warnings = ["all"]
